server:
  port: 8888

spring:
  application:
    name: code-generator
  profiles:
    active: dev
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/my_mall?&characterEncoding=utf8"

code-generator:
  author: "Tomatos"
  package-name: "org.demo.study"
  table-prefix: "sys_" # 实际的类名 = 表名去掉表前缀首写第一个大写字母
  path-rule-map:
    entity:
      model-path: "entity"
      suffix: "DO"
    condition-entity:
      model-path: "condition"
      suffix: "Condition"
    dto-entity:
      model-path: "dto"
      suffix: "DTO"
    controller:
      model-path: "controller"
      suffix: "Controller"
    service-interface:
      model-path: "service"
      suffix: "Service"
      prefix: "I"
    service:
      model-path: "service/impl"
      suffix: "ServiceImpl"
    mapper:
      model-path: "mapper"
      suffix: "Mapper"
    mapper-xml:
      model-path: "mapper/xml"
      suffix: "Mapper"